apiVersion: v1
kind: Secret
metadata:
  name: secrets-grafana
  namespace: monitoring
type: Opaque
stringData:
  admin-user: ENC[AES256_GCM,data:AU1/HCs=,iv:hQaejyt013oETI0qNQH2IKEQpC1jTqeb12yEh3ScqcU=,tag:dGEU1c0KySn8nzkzIQ8wUA==,type:str]
  admin-password: ENC[AES256_GCM,data:4S7cNGQQ9+dDEM0ozFq1ejY93/deHLEJ2K9NPJn6u2BgNrZUNCuaH4rs8796R5B5r00jN91Zm/63BndKr7Q1nw==,iv:91dwHkwgarqlI+PJzPFngb6+joAytCKEQfghh/obz+k=,tag:D6hN8N7h8Qa+9UVkGhUfOA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RUsrYWFhWi82YUtickk3
        MGw3UStUY2NodjRpZHVvaUxtZHJVOHZNdm5zCmxhTzVZOVRhY1YzNHB5MHU1azcz
        akY5TGpzc1hRQWp6SHhoNlBOSzhKVUEKLS0tIEhIakdKRjNwN1FZcHRGK2V0WG5I
        RmlrRWtWRmFxbWkvUmtmKzBoaXlBbUkKqOPvm1jBlI3z9/zhLl8hP5/mk2+JNfno
        O3JPriKbs6uaB3cZFl8UfTt0qCMX/1iqirgkLj9usOw55D7MWSndFQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-07-12T19:54:15Z"
  mac: ENC[AES256_GCM,data:20/gJ24rjjepuO8Iiq5QFlDT/BhlbfkQd50AK0oShloxHT1Gi6o8D4B13jJRMSfYNGGs8FcTUAjNJt5jJZojJ4Fq5zzzri0ChSPm8iZawEs3HTw1Wp4FAvHIAL50NHjNNpj2fu3nhBJfRFgfeKIGOAloeSp5zsQk/DQBn6uEjIE=,iv:cseDvIIAhoAU/4bla0Glp4wbnJkbznnyDbgbxtaXpv4=,tag:T8qlHI18pSdeHsar2Lo8bw==,type:str]
  pgp: []
  encrypted_regex: ^(stringData)$
  version: 3.9.0
