---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-external
  namespace: traefik-system
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: 28.3.0
  interval: 60m
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  values:
    tlsStore:
      default:
        defaultCertificate:
          secretName: wildcard-layertwo-dev-tls
    service:
      annotations:
        metallb.universe.tf/address-pool: external
        external-dns.alpha.kubernetes.io/enabled: "true"
        external-dns.alpha.kubernetes.io/hostname: "traefik-external.layertwo.dev"
    ingressClass:
      enabled: true
      default: false
      name: external
    ingressRoute:
      dashboard:
        annotations:
          external-dns.alpha.kubernetes.io/enabled: "true"
          external-dns.alpha.kubernetes.io/hostname: "traefik-external.layertwo.dev"
        entryPoints: ["websecure"]
        matchRule: Host(`traefik-external.layertwo.dev`)
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
        ingressClass: external
      kubernetesIngress:
        ingressClass: external
