---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-external
  namespace: traefik-system
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: 30.1.0
  interval: 60m
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  values:
    ports:
      web:
        redirectTo:
          port: websecure
    tlsStore:
      default:
        defaultCertificate:
          secretName: wildcard-layertwo-dev-tls
    service:
      spec:
        externalTrafficPolicy: Local
      annotations:
        metallb.universe.tf/address-pool: external
        external-dns.alpha.kubernetes.io/enabled: "true"
        external-dns.alpha.kubernetes.io/hostname: "traefik-external.layertwo.dev"
    ingressClass:
      enabled: true
      default: false
      name: &ingressName external
    ingressRoute:
      dashboard:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/enabled: "true"
          external-dns.alpha.kubernetes.io/hostname: "traefik-external.layertwo.dev"
        entryPoints: ["websecure"]
        matchRule: Host(`traefik-external.layertwo.dev`)
    providers:
      kubernetesCRD:
        enabled: true
        allowCrossNamespace: true
        ingressClass: *ingressName
      kubernetesIngress:
        enabled: true
        ingressClass: *ingressName
        publishedService:
          enabled: false
    logs:
      access:
        enabled: true
    globalArguments: []
    deployment:
      replicas: 2
