---
apiVersion: v1
kind: Namespace
metadata:
  name: cattle-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: system-upgrade-controller
  namespace: cattle-system
spec:
  interval: 30m
  url: https://github.com/rancher/system-upgrade-controller
  ref:
    tag: v0.13.4
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-upgrade-controller
  namespace: cattle-system
spec:
  interval: 15m
  targetNamespace: cattle-system
  sourceRef:
    kind: GitRepository
    name: system-upgrade-controller
  prune: true
