---
apiVersion: v1
kind: Namespace
metadata:
  name: system-upgrade
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-upgrade-controller
  namespace: flux-system
spec:
  interval: 15m
  targetNamespace: system-upgrade
  sourceRef:
    kind: GitRepository
    name: system-upgrade-controller
    namespace: flux-system
  prune: false
