apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: internal-restricted
  namespace: traefik-system
spec:
  ipWhiteList:
    sourceRange:
      - 192.168.255.0/24
      - 192.168.4.0/24
      - 192.168.2.0/24
