---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: traefik-internal
  namespace: traefik-system
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: v28.0.0
  interval: 60m
  values:
    service:
      annotations:
        external-dns.alpha.kubernetes.io/enabled: "true"
        external-dns.alpha.kubernetes.io/hostname: "proxy-internal.layertwo.dev"
        metallb.universe.tf/address-pool: internal
    ingressRoute:
      dashboard:
        annotations:
          external-dns.alpha.kubernetes.io/enabled: "true"
          external-dns.alpha.kubernetes.io/hostname: "traefik-internal.layertwo.dev"
          external-dns.alpha.kubernetes.io/target: "proxy-internal.layertwo.dev"
        entryPoints: ["websecure"]
        matchRule: Host(`traefik-internal.layertwo.dev`)
        #middlewares: ["internal-restricted"]
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
    logs:
      access:
        enabled: true
