---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cloudflare-ddns
  namespace: traefik-system
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
          - name: main
            imagePullPolicy: IfNotPresent
            securityContext:
              runAsNonRoot: false
              readOnlyRootFilesystem: true
              #capabilities:
                #drop:
                #  - ALL
              privileged: false
              allowPrivilegeEscalation: false
            env:
              - name: TOKEN
                valueFrom:
                  secretKeyRef:
                    key: TOKEN
                    name: cloudflare-ddns
                    optional: false
              - name: ZONE_ID
                valueFrom:
                  secretKeyRef:
                    key: ZONE_ID
                    name: cloudflare-ddns
                    optional: false
              - name: DNS_NAME
                value: "proxy-external.layertwo.dev"
              - name: ENABLE_PROXY
                value: "true"
            image: ghcr.io/layertwo/cloudflare-ddns:latest@sha256:c612e43b154f4b42704e07c0c4da0272edb5e34b263d8e5d9070f995d1a38f15
          restartPolicy: OnFailure
          dnsConfig:
            nameservers:
              - 1.1.1.1
