---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cloudflare-ddns
  namespace: traefik-system
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
          - name: main
            imagePullPolicy: IfNotPresent
            securityContext:
              runAsNonRoot: false
              readOnlyRootFilesystem: true
              #capabilities:
                #drop:
                #  - ALL
              privileged: false
              allowPrivilegeEscalation: false
            env:
              - name: TOKEN
                valueFrom:
                  secretKeyRef:
                    key: TOKEN
                    name: secrets-cloudflare-ddns
                    optional: false
              - name: ZONE_ID
                valueFrom:
                  secretKeyRef:
                    key: ZONE_ID
                    name: secrets-cloudflare-ddns
                    optional: false
              - name: DNS_NAME
                valueFrom:
                  secretKeyRef:
                    key: DNS_NAME
                    name: secrets-cloudflare-ddns
                    optional: false
              - name: ENABLE_PROXY
                value: "true"
            image: ghcr.io/layertwo/cloudflare-ddns:latest@sha256:b5355a0fe537b70433c85194bb54f0548b0f6bdb057e7366cf056171bb1c1286
          restartPolicy: OnFailure
          dnsConfig:
            nameservers:
              - 1.1.1.1
