---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cloudflare-ddns
  namespace: traefik-system
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
          - name: main
            imagePullPolicy: IfNotPresent
            securityContext:
              runAsNonRoot: false
              readOnlyRootFilesystem: true
              #capabilities:
                #drop:
                #  - ALL
              privileged: false
              allowPrivilegeEscalation: false
            env:
              - name: TOKEN
                valueFrom:
                  secretKeyRef:
                    key: TOKEN
                    name: cloudflare-ddns
                    optional: false
              - name: ZONE_ID
                valueFrom:
                  secretKeyRef:
                    key: ZONE_ID
                    name: cloudflare-ddns
                    optional: false
              - name: DNS_NAME
                value: "proxy-external.layertwo.dev"
            image: ghcr.io/layertwo/cloudflare-ddns:latest@sha256:40513b34ae6ba61a252dd7f19e64ab42a3a4aad03c57738ea359a96c46010784
          restartPolicy: OnFailure
          dnsConfig:
            nameservers:
              - 1.1.1.1
