apiVersion: v1
kind: Secret
metadata:
  name: secrets-emqx-init-user
  namespace: home-assistant
type: Opaque
stringData:
  init-user.json: ENC[AES256_GCM,data:htY1hPZVkHMIvixCA7jIV45ErZxOHCSItXn35RwtPnxAN81a4qRa0OFhSDjRk3Hp/C3xk6Rt1IMhBh0pmpfKDICWyV/3NMGoWy6vkydhRH74qyhyE+bZyjSEuyVu/jP1K02HJO4+zezFJb91f9KC4IQbRSJs9jnLkLfyrw==,iv:ivFHR9c6Ni852picRg/jrtEZezoUaqk7ZfizXtGk4QE=,tag:6yasV3pn3bUdI22YBGrQ1g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZODMvcG83NW9uM3l1UGxr
        aFcxRXdKSDhtdmFManlrTmdTNmdGZTNHVEdzCllUVXQ5YXlYbXI3SktEZ3JRQlhR
        YlJoblUzTndXbm9kRXh3KysyZEFxcXcKLS0tIEVVM3JMKzlHTzV3Z3ZPSTg5NWZY
        ODZHZCsyaUQ1UGttbTBXR3krSE43cjQKYeNh/vfIf/8NEgh3TcKBnhHEJDm5jf2/
        0MVb3OVdxc1FtdpReQrL1feyTgkXpe5DwgffYLoIMRNoPaTSfrN1kQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-11-18T00:16:39Z"
  mac: ENC[AES256_GCM,data:fsutlQz8V+BenXTcETvVMwi4b/w2FNj4mY1wjmuhuATnWM5dmfOZM0Gru6X2S2Qe1UCAgKfSPu0CbARvso6/4ol8lG96t8GdejvJNAxjcowdLXPcS5snTOI1Rw0PfOEpQ6CUSoXI052mbvjiAAZ7kgSVQ6cfPYdNV2wuaEkkFEU=,iv:7g8WfQ7BBcA4VcnFKV8OM7BxhQBQOoFt6VEki9tUakg=,tag:MpHfTTeQQY6CA+igSiQb4A==,type:str]
  pgp: []
  encrypted_regex: ^(stringData)$
  version: 3.9.1
