---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-dns-cloudflare
  namespace: external-dns
spec:
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      version: 1.14.5
  interval: 60m
  values:
    fullnameOverride: *app
    provider:
      name: cloudflare
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: external-dns-cloudflare
            key: token
    extraArgs:
      - --annotation-filter=external-dns.alpha.kubernetes.io/enabled in (true)
      - --cloudflare-dns-records-per-page=1000
      #- --cloudflare-proxied
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      - --crd-source-kind=DNSEndpoint
      - --events
      - --ignore-ingress-tls-spec
      - --ingress-class=external
      - --traefik-disable-legacy
    policy: sync
    sources:
      - service
      - ingress
      - traefik-proxy
    domainFilters:
      - layertwo.dev
    serviceMonitor:
      enabled: false
    resources:
      requests:
        cpu: 10m
        memory: 16Mi
      limits:
        memory: 64Mi
