apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloudflare
    namespace: external-dns
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:uLBzQf67yHGvMIoWuvzxyz4HXcdocDG/Nw5s71KsjihjCsxWXDu84w==,iv:MSxMd4cSZ7ydCr9DUG1yTbprJZbwXn8arzNtyYvXgBo=,tag:4FXWTvN+geklcAV4ITlWGg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4b0ROTG4rZHp1N3ZPVEVn
            UE11cXpkbFFkRXF4Ui9qK3ZsZkxYa0ZoUlVBCjNSZGtMOHJHamlxMm5VcVFXWUJH
            NS9iQVNNYzNLYWVMaHVmeW93eGJhRWMKLS0tIHBGdWtzVml0emdtZmVWblkwMWFE
            RTVnQ3VFUVNHUnZkVis5T2xhQThSM1UKURs8U0UeCYpusiqaug8wEG43gkBvXIBQ
            biMkuOaM6ZF5xSeRiMsHBTfI7yjpuQDESdnhIGXHmUgAslGHML06nA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-21T07:51:02Z"
    mac: ENC[AES256_GCM,data:U/ooXMB9ldBD0CcYQLKZcB1XFF17Wqyjk+j60r76tfSSHmqfaQZpcSY0dQHN+6TH9C8sIYve0v8L2sPIGRiLwo1gUzAHEJn4IU6iFI5ETjMWIE7xia504fhU5teM/LzilXyBx8o2zhtzeIpATNvS0qDWgzCRUsAUiBOeQRfAFQ4=,iv:gq+A6sRiPJU/yWOrSFyBWiWfseofafjVC1raQWUutpA=,tag:oC9zsBARCCmRtEbkUZ8DKw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
