---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  chart:
    spec:
      chart: rancher
      sourceRef:
        kind: HelmRepository
        name: rancher-stable
        namespace: flux-system
      version: 2.8.5
  interval: 60m
  values:
    hostname: rancher.layertwo.dev
    noProxy: 127.0.0.0/8,10.0.0.0/8,cattle-system.svc,172.16.0.0/12,192.168.0.0/16,.svc,.cluster.local
    ingress:
      tls:
        source: secret
        secretName: tls-rancher-ingress
      extraAnnotations:
        cert-manager.io/issuer-kind: ClusterIssuer
        cert-manager.io/issuer-name: letsencrypt-prod-dns
        external-dns.alpha.kubernetes.io/enabled: "true"
        external-dns.alpha.kubernetes.io/hostname: "rancher.layertwo.dev"
        external-dns.alpha.kubernetes.io/target: "proxy-internal.layertwo.dev"
      ingressClassName: traefik-internal
    privateCA: false
