---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    name: cert-manager
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      version: 1.14.5
  interval: 60m
  values:
    installCRDs: true

    resources:
      requests:
        cpu: 10m
        memory: 36Mi
      limits:
        memory: 128Mi

    extraArgs:
      # When this flag is enabled, secrets will be automatically removed when the certificate resource is deleted
      - --enable-certificate-owner-ref=true

    global:
      leaderElection:
        namespace: cert-manager

    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
        labels:
          release: monitoring

    webhook:
      resources:
        requests:
          cpu: 10m
          memory: 18Mi
        limits:
          memory: 128Mi

    cainjector:
      resources:
        requests:
          cpu: 20m
          memory: 72Mi
        limits:
          memory: 172Mi
