---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-prowlarr
  namespace: mediabox
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  imageName: ghcr.io/cloudnative-pg/postgresql:16.4
  bootstrap:
    initdb:
      database: prowlarr_main
      owner: prowlarr
  storage:
    storageClass: sunbeam-nfs-csi
    size: 4Gi
