---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: mediabox
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  values:
    controllers:
      main:
        containers:
          prowlarr:
            image:
              repository: ghcr.io/onedr0p/prowlarr
              tag: 1.18.0.4543
            env:
              TZ: "Etc/UTC"
              PROWLARR__INSTANCE_NAME: Prowlarr
              PROWLARR__PORT: &port 9696
              PROWLARR__LOG_LEVEL: info
              PROWLARR__ANALYTICS_ENABLED: "False"
              PROWLARR__POSTGRES_HOST:
                valueFrom:
                  secretKeyRef:
                    name: cnpg-prowlarr-app
                    key: host
              PROWLARR__POSTGRES_MAIN_DB: prowlarr_main
              PROWLARR__POSTGRES_LOG_DB: prowlarr_log
              PROWLARR__POSTGRES_USER:
                valueFrom:
                  secretKeyRef:
                    name: cnpg-prowlarr-app
                    key: user
              PROWLARR__POSTGRES_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: cnpg-prowlarr-app
                    key: password
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 512Mi
    defaultPodOptions:
      dnsConfig:
        nameservers:
          - 1.1.1.1
        options:
          - { name: ndots, value: "1" }
    service:
      main:
        enabled: true
        controller: main
        ports:
          http:
            enabled: true
            port: *port
            protocol: HTTP
    persistence:
      config:
        enabled: true
        storageClass: sunbeam-nfs-csi
        accessMode: "ReadWriteOnce"
        size: 1Gi
        advancedMounts:
          main:
            prowlarr:
              - path: /config
