---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-internal
  namespace: traefik-system
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: 31.1.0
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  interval: 60m
  values:
    ports:
      web:
        redirectTo:
          port: websecure
    service:
      spec:
        externalTrafficPolicy: Local
      annotations:
        external-dns.alpha.kubernetes.io/enabled: "true"
        external-dns.alpha.kubernetes.io/hostname: "proxy-internal.layertwo.dev"
        kubernetes.io/ingress.class: &ingressName internal
        metallb.universe.tf/address-pool: internal
    ingressClass:
        enabled: true
        default: true
        name: *ingressName
    ingressRoute:
      dashboard:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/enabled: "true"
          external-dns.alpha.kubernetes.io/hostname: "traefik-internal.layertwo.dev"
          external-dns.alpha.kubernetes.io/target: "proxy-internal.layertwo.dev"
        entryPoints: ["websecure"]
        matchRule: Host(`traefik-internal.layertwo.dev`)
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
        ingressClass: *ingressName
      kubernetesIngress:
        ingressClass: *ingressName
    logs:
      access:
        enabled: true
    globalArguments: []
    deployment:
      replicas: 2
