---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-authentik
  namespace: authentik
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised
  imageName: ghcr.io/cloudnative-pg/postgresql:16.5
  bootstrap:
    initdb:
      database: authentik
      owner: authentik
  storage:
    storageClass: sunbeam-nfs-csi
    size: 4Gi
  walStorage:
    storageClass: sunbeam-nfs-csi
    size: 4Gi
