---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      version: 1.14.5
  interval: 60m
  values:
    logLevel: debug
    interval: 2m
    provider: cloudflare
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: external-dns-cloudflare
            key: token
    extraArgs:
      - --annotation-filter=external-dns.alpha.kubernetes.io/enabled in (true)
      - --traefik-disable-legacy
    # policy sync for fully handle the domain
    policy: sync
    sources:
      - service
      - ingress
      - traefik-proxy
    domainFilters:
      - layertwo.dev
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: monitoring
    resources:
      requests:
        cpu: 10m
        memory: 14Mi
      limits:
        memory: 64Mi
