apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: truenas-nfs
    namespace: democratic-csi
spec:
    chart:
        spec:
            chart: democratic-csi
            sourceRef:
                kind: HelmRepository
                name: democratic-csi
                namespace: flux-system
            version: 0.14.6
    interval: 60m
    values:
        csiDriver:
            # should be globally unique for a given cluster
            name: org.democratic-csi.nfs
            fsGroupPolicy: File
        storageClasses:
            - name: sunbeam-nfs-csi
              defaultClass: false
              reclaimPolicy: Delete
              volumeBindingMode: Immediate
              allowVolumeExpansion: true
              parameters:
                fsType: nfs
              mountOptions:
                - noatime
                - nfsvers=4
              secrets:
                provisioner-secret: null
                controller-publish-secret: null
                node-stage-secret: null
                node-publish-secret: null
                controller-expand-secret: null
        driver:
            config:
                driver: freenas-api-nfs
                instance_id: null
                httpConnection:
                    protocol: https
                    host: sunbeam.layertwo.lan
                    port: 443
                    apiKey: ENC[AES256_GCM,data:jy0RLr2ZbWSm3WF4E6Ak1lM1a89oylmVJgpZAaSHk+M9Eiuc+KeBf+ca4/vu9CQNrsoBxd3yGMX79d7lk6c97DzR,iv:8WMZ5dCvMSkN1S8yhPjhJ8V61g8w0ut7rFn3CgnFJfU=,tag:Xfh+XNz3GC45qrL/1/MOVA==,type:str]
                    allowInsecure: true
                zfs:
                    datasetParentName: storage0/kubernetes/persistent-volume/nfs/volumes
                    detachedSnapshotsDatasetParentName: storage0/kubernetes/persistent-volume/nfs/snapshots
                    datasetEnableQuotas: true
                    datasetEnableReservation: false
                    datasetPermissionsMode: "0777"
                    datasetPermissionsUser: 3001
                    datasetPermissionsGroup: 3001
                nfs:
                    shareHost: sunbeam.layertwo.lan
                    shareAlldirs: false
                    shareAllowedHosts:
                        - 172.31.0.10
                        - 172.31.0.11
                        - 172.31.0.12
                    shareAllowedNetworks: []
                    shareMaprootUser: kubernetes
                    shareMaprootGroup: kubernetes
                    shareMapallUser: ""
                    shareMapallGroup: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWamxTRXZZMUtkZDFxUy9Y
            YjJLZXJQa1A5TTRJSHdXVVZleVZiMzJydkZzCnhPdUhkK3JZdEFRcU44NmZKblhE
            OWNvaE5SNk5rVnNkamNaWUdIZ3RDWUEKLS0tIDdrYnZaNFhsNGpnbDRhL1N3akdQ
            T2REQjBQUmRDWW5lU1NwdEQ0TmtDZmsKT+RnE5pE23eIo8f/u5YAUmWaBVtZiXjx
            p3ccYRHQ/z1RV1/VGcdvWzHU688BhViMfUc+fOYn5NDV8lg5FS430w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-07T04:14:38Z"
    mac: ENC[AES256_GCM,data:Cr/g5C0B7WrMrIzJrbIFacCjrN1P0a1nMuRiNbGHapPaUzCfZZKg3Xuj0X1JLIv8EF84P31kObV8MoIp+kJnui8UWa7bj+npmLKZ24CIW4a+1oWiNlZi4GqeNhbdl8oRZLJWxknFmZ0fgURaQWolUGzSy4MoHPThbUS6p0avlBg=,iv:YcHiV92vS31zKkVrZFFRLcHu46T5H1KfXaKQqY/l0kU=,tag:XTUnuKXZTojNXPZKSn8kLg==,type:str]
    pgp: []
    encrypted_regex: ^(apiKey)$
    version: 3.8.1
