apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: purelb

resources:
- https://gitlab.com/api/v4/projects/purelb%2Fpurelb/packages/generic/manifest/0.0.1/purelb-complete.yaml
- config.yml
