apiVersion: v1
kind: Secret
metadata:
    name: truenas-api-secret
    namespace: democratic-csi
stringData:
    apiKey: ENC[AES256_GCM,data:Td+eEOmoL9SVL0AQJUNvSBW4c4lQdRuGc/O0R3liPVqjE4ABSwyRIC4e2JpGZyv9/RQ0KKGn0V75pN3fi/SaZ17R,iv:h9iiMZbeNiG7Ra6JHL2lXEpEFQrlaVdIH7nzkMkraUM=,tag:7KTIRjFNOlVodQVewbFDNA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4SEpOS2o3Zm9LN0hVSS9s
            WERXSDR5QkMrMTZQRU1oSFBBRVpPTnIreGtNClJUdy9OSkl1TWpPeTlMQU44VTRt
            d1JneGdTZ2JhcFAyRUduaWtLKytibDAKLS0tIHI1em9OTll4QjAvaS92REhvQVl1
            c1grRmFTcitCZEh5SWtRUVNNMWMrK2sK+psc8KUohOMFR617OtPaZfuK5Yl4CCBl
            eGXVOKCzGU4osnNyMk/IMPpNNW0qLzr/sA+8IQprhpGPUiBg/qazdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-10T06:38:52Z"
    mac: ENC[AES256_GCM,data:I9YVo1BAOn0IsQoJi3jhFzy+nZ4rtHq4Gm7FNL4gucblOWsoIm3Qq8+c+8qVSx6P/ik9Sqi+JwHsnzGzcaZWHKWL41W+Ic46oIEvFr/oh8zvdydh5LvEGYxqxoSwW/zRcu1TEI7HLnroGjOJlJiENrFBJLEfMbGBs84wN/1iPiI=,iv:4n5QNcDmBYGyIabgdtXL2Qi45NoaKjc51LsKPBDbgO4=,tag:BDO5ljLS1BQts/xURRlbPw==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.8.1
