---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jellyfin-config
  namespace: mediabox
  labels:
    app: "mediabox"
    app.kubernetes.io/instance: "jellyfin"
    app.kubernetes.io/name: "jellyfin"
    release: "jellyfin"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 64Gi
