
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: home-assistant
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      main:
        type: statefulset
        containers:
          main:
            image:
              repository: ghcr.io/koenkk/zigbee2mqtt
              tag: 1.40.0
            env:
              TZ: "Etc/UTC"
              LOGLEVEL: info
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: 15m
                memory: 150Mi
    service:
      main:
        enabled: true
        controller: main
        ports:
          http:
            port: 8080
    persistence:
      config:
        enabled: true
        storageClass: sunbeam-nfs-csi
        accessMode: "ReadWriteOnce"
        size: 1Gi
        globalMounts:
          - path: /app/data
