---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      main:
        containers:
          home-assistant:
            image:
              repository: ghcr.io/onedr0p/home-assistant
              tag: 2024.8.1@sha256:d315bfaf6e9d5f612f4d773217c80cfb4b87f582b4278257739f792651221cdc
            env:
              TZ: Etc/UTC
              HASS_POSTGRES_URL:
                valueFrom:
                  secretKeyRef:
                    name: cnpg-home-assistant-app
                    key: uri
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop: ["ALL"]
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 2Gi
    defaultPodOptions:
      securityContext:
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    service:
      main:
        enabled: true
        controller: main
        ports:
          http:
            enabled: true
            port: 8123
            protocol: HTTP
    persistence:
      config:
        enabled: true
        storageClass: sunbeam-nfs-csi
        accessMode: "ReadWriteOnce"
        size: 32Gi
        globalMounts:
          - path: /config
      configmap:
        enabled: true
        type: configMap
        name: home-assistant-configmap
        globalMounts:
          - path: /config/configuration.yaml
            subPath: configuration.yaml
          - path: /config/automations.yaml
            subPath: automations.yaml
          - path: /config/scenes.yaml
            subPath: scenes.yaml
          - path: /config/scripts.yaml
            subPath: scripts.yaml
      logs:
        type: emptyDir
        globalMounts:
          - path: /config/logs
      tts:
        type: emptyDir
        globalMounts:
          - path: /config/tts
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
