apiVersion: v1
kind: Secret
metadata:
    name: secrets-authentik
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:uC+KGQQieSUbLDcRGhF3VUtJJzsxPdPIp54I1guoCpiTdBYMPF9H8+7EtnssWlbXdptSjDOc0rKUa9/XO8xZnw==,iv:b93ydnXvldJ9CvW9GDlS80CedkzyiTUZrxRQ+upviRE=,tag:C42UHDfJXd1vd/M62lTEMA==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:OiZTQbd7qBJRihZf5wqeDaGPKqe3l9WYWtCE1p3XkyIJ6Lv1+O5s9EC5gTnF7Y1PsSVE30sdZ/ZKF7pzxnU12w==,iv:+w/Amfp1Qn6y7nLEipmRKwkHf1Tz+3JWe49Ji9HHK7o=,tag:TwTBYxO5ID+wosKKbs2IeA==,type:str]
    AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:aLkdcsnDJigKKK0Br+i5efSiq8oltIaBYvzMKkiGLJ3CaLe36EuHF1INPSjWKdW2EbsDblrgEprvhxAHSNWsSA==,iv:BSJi6T8bAKuM6nSfEF/yHIX0wEvrcRJr2w4N1Rn5+68=,tag:ZNF8TvVQl7KhHfpaTbJa7A==,type:str]
    AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:5LEtaLNpT3wCGRzT/eYvjzIg,iv:Wqc+ucpVCrsDTE4AVU6F/mvAvPkzWTKLUI1fRLogUq8=,tag:BGqYqidsN2/NzsGq+ofHLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrbTVnSVlpRm56Z0NRcGIv
            SUM3WkR6OUhKcVhYZlByanB3NTRNdjFuM1VJCmU3RjNzMm5iT2FRdHJzcm1rSFFF
            cURNbllNMGJhSFNFSmg0cCtaUm5UMXMKLS0tIDF0NGVHOFBnTTY4clM1L09vd3dr
            Mkc2bk0zdnNKYVFoaTU0UGNDOFJGZEUKl1TJ5m0h8ms3YnMVniUKvcUROa90H04u
            5aWUuBUvc6k/1qE9HNL4oFG9wDEK+wGXqmb/QZu6ssnKgzMKHTQesA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-29T06:13:00Z"
    mac: ENC[AES256_GCM,data:nauPqO9Rm+m4J7ZJMiV88U2xBzIE8eckybpnZHhY2ShamvBuWvTRyQfcA8R7gUo00rF+dnhpOA7X3TSm/Xi/VwCesi6+RlXnwhU45rMsO/IZnOWofFBHvwkhShx8D3n0FyZ8rzZ5RKsHZVNnwUpwzFIPi9ucdEdYnTbDi9MZLGI=,iv:avj5AYfuspqMLqOY6NXfTFSmO7onUQgBwRbF8vYAmnY=,tag:MLW65GvW9o7r0g5OWWanIA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
