---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-dns-unifi
  namespace: external-dns
spec:
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      version: 1.14.5
  interval: 60m
  values:
    fullnameOverride: *app
    logLevel: debug
    interval: 2m
    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/kashalls/external-dns-unifi-webhook
          tag: v0.2.0@sha256:4f0d996ba6932f38e921b0717ba44cb58b7d687dcf6a55c9d3843396d23b22d1
        env:
          - name: UNIFI_HOST
            valueFrom:
              secretKeyRef:
                name: &secret external-dns-unifi
                key: UNIFI_HOST
          - name: UNIFI_USER
            valueFrom:
              secretKeyRef:
                name: *secret
                key: UNIFI_USER
          - name: UNIFI_PASS
            valueFrom:
              secretKeyRef:
                name: *secret
                key: UNIFI_PASS
        livenessProbe:
          httpGet:
            path: /healthz
            port: http-wh-metrics
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readyz
            port: http-wh-metrics
          initialDelaySeconds: 10
          timeoutSeconds: 5
    extraArgs:
      - --annotation-filter=kubernetes.io/ingress.class in (internal)
      - --ignore-ingress-tls-spec
      - --traefik-disable-legacy
    policy: sync
    sources:
      - service
      - ingress
      - traefik-proxy
    domainFilters:
      - layertwo.dev
      - layertwo.lan
