---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik-system
  labels:
    name: traefik
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 60m
  url: https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik-system
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: v28.0.0
  interval: 60m
  values:
    tlsStore:
      default:
        defaultCertificate:
          secretName: wildcard-layertwo-dev-tls
    service:
      annotations:
        external-dns.alpha.kubernetes.io/enabled: "true"
        external-dns.alpha.kubernetes.io/hostname: "proxy-internal.layertwo.dev"
    ingressRoute:
      dashboard:
        annotations:
          external-dns.alpha.kubernetes.io/enabled: "true"
          external-dns.alpha.kubernetes.io/hostname: "traefik-internal.layertwo.dev"
          external-dns.alpha.kubernetes.io/target: "proxy-internal.layertwo.dev"
        entryPoints: ["websecure"]
        matchRule: Host(`traefik-internal.layertwo.dev`)
        middlewares: ["internal-restricted"]
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
