apiVersion: v1
kind: Service
metadata:
  name: jellyfin-autodiscovery
  namespace: mediabox
  labels:
    app: "jellyfin"
    app.kubernetes.io/instance: "jellyfin"
    app.kubernetes.io/name: "jellyfin"
    release: "jellyfin"
    service.name: "autodiscovery"
spec:
  type: ClusterIP
  publishNotReadyAddresses: false
  ports:
    - name: autodiscovery
      port: 7359
      protocol: UDP
      targetPort: 7359
  selector:
    pod.name: main
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/instance: jellyfin
