---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hajimari
  namespace: hajimari
spec:
  chart:
    spec:
      chart: hajimari
      sourceRef:
        kind: HelmRepository
        name: hajimari
        namespace: flux-system
      version: 2.0.2
  interval: 60m
  values:
    hajimari:
      defaultEnable: true
    persistence:
      data:
        enabled: true
        storageClass: sunbeam-nfs-csi
        type: pvc
        accessMode: ReadWriteOnce
        size: 1Gi
