---
apiVersion: v1
kind: Namespace
metadata:
  name: hajimari
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: hajimari
  namespace: flux-system
spec:
  interval: 60m
  url: https://hajimari.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hajimari
  namespace: hajimari
spec:
  chart:
    spec:
      chart: hajimari
      sourceRef:
        kind: HelmRepository
        name: hajimari
        namespace: flux-system
  interval: 60m
  values:
    hajimari:
      defaultEnable: true
    ingress:
      main:
        enabled: true
        className: "traefik-internal"
        annotations:
          external-dns.alpha.kubernetes.io/enabled: "true"
          external-dns.alpha.kubernetes.io/hostname: "inside.layertwo.dev"
          external-dns.alpha.kubernetes.io/target: "traefik-external.layertwo.dev"
        hosts:
        - host: inside.layertwo.dev
          paths:
            - path: /
              pathType: Prefix
              service:
                name: hajimari
                port: 3000
        tls:
          - secretName: wildcard-layertwo-dev-tls
            hosts:
              - inside.layertwo.dev
