---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-cnpg
  namespace: authentik
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.2
  bootstrap:
    initdb:
      database: authentik
      owner: authentik
  storage:
    size: 4Gi
  walStorage:
    size: 4Gi
