---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 5m
  chart:
    spec:
      chart: authentik
      version: 2024.4.2
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
  values:
    server:
      ingress:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/enabled: "true"
          external-dns.alpha.kubernetes.io/hostname: "authentik.layertwo.dev"
          external-dns.alpha.kubernetes.io/target: "proxy-internal.layertwo.dev"
          kubernetes.io/ingress.class: "internal"
        hosts:
          - authentik.layertwo.dev
      env:
        - name: AUTHENTIK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: AUTHENTIK_SECRET_KEY
              name: secrets-authentik
        - name: AUTHENTIK_BOOTSTRAP_PASSWORD
          valueFrom:
            secretKeyRef:
              key: AUTHENTIK_BOOTSTRAP_PASSWORD
              name: secrets-authentik
        - name: AUTHENTIK_BOOTSTRAP_TOKEN
          valueFrom:
            secretKeyRef:
              key: AUTHENTIK_BOOTSTRAP_TOKEN
              name: secrets-authentik
        - name: AUTHENTIK_BOOTSTRAP_EMAIL
          valueFrom:
            secretKeyRef:
              key: AUTHENTIK_BOOTSTRAP_EMAIL
              name: secrets-authentik
        - name: AUTHENTIK_POSTGRESQL__HOST
          valueFrom:
            secretKeyRef:
              name: authentik-cnpg-app
              key: host
        - name: AUTHENTIK_POSTGRESQL__NAME
          valueFrom:
            secretKeyRef:
              name: authentik-cnpg-app
              key: dbname
        - name: AUTHENTIK_POSTGRESQL__USER
          valueFrom:
            secretKeyRef:
              name: authentik-cnpg-app
              key: user
        - name: AUTHENTIK_POSTGRESQL__PASSWORD
          valueFrom:
            secretKeyRef:
              name: authentik-cnpg-app
              key: password
    worker:
      env:
        - name: AUTHENTIK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: AUTHENTIK_SECRET_KEY
              name: secrets-authentik
        - name: AUTHENTIK_BOOTSTRAP_PASSWORD
          valueFrom:
            secretKeyRef:
              key: AUTHENTIK_BOOTSTRAP_PASSWORD
              name: secrets-authentik
        - name: AUTHENTIK_BOOTSTRAP_TOKEN
          valueFrom:
            secretKeyRef:
              key: AUTHENTIK_BOOTSTRAP_TOKEN
              name: secrets-authentik
        - name: AUTHENTIK_BOOTSTRAP_EMAIL
          valueFrom:
            secretKeyRef:
              key: AUTHENTIK_BOOTSTRAP_EMAIL
              name: secrets-authentik
        - name: AUTHENTIK_POSTGRESQL__HOST
          valueFrom:
            secretKeyRef:
              name: authentik-cnpg-app
              key: host
        - name: AUTHENTIK_POSTGRESQL__NAME
          valueFrom:
            secretKeyRef:
              name: authentik-cnpg-app
              key: dbname
        - name: AUTHENTIK_POSTGRESQL__USER
          valueFrom:
            secretKeyRef:
              name: authentik-cnpg-app
              key: user
        - name: AUTHENTIK_POSTGRESQL__PASSWORD
          valueFrom:
            secretKeyRef:
              name: authentik-cnpg-app
              key: password
    redis:
      enabled: true
    postgresql:
      enabled: false
