---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-outline
  namespace: outline
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised
  imageName: ghcr.io/cloudnative-pg/postgresql:16.5
  storage:
    storageClass: sunbeam-nfs-csi
    size: 16Gi
