apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-cloudflare
    namespace: cert-manager
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:iwDlE/3lV67kMsuFpAcADR7+nukFMOVP/X/DOFngH3qIEq4wLCeGVA==,iv:zNqGdAA0sa0B18ieR0v/nWfwlHF1qdiwxDUO/vVuk4A=,tag:ShOOBE8f0aHYzQMogs4SbQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1RHhJVHBYbjRlajFqRU5k
            RVFoK0xBVFZFaTFwMGVFbE5sYjE2WjN2dFZBClFYaWNuc1dlVTJEQitqeDFMWmJu
            T01PYjRRUnRTOEtlUkJ1aWtKTE1iZlUKLS0tIGptL0tVaHFNOVFNSmIySXF3Wjlw
            elpIcWlaQzhTT25ZbmZ5QTFkRUNVMWcKWWA+VmHZgQarUgDcE6msELUoNunsJhzH
            bvladSx3mgmRoxvGBprtvH2oyujmbg6YNqKcHYU6PBlfSZ5O9QKGOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-21T07:26:17Z"
    mac: ENC[AES256_GCM,data:Ll/7JLYw/h8HFdK+5QUQNkzQWfGwQf/wPvK0dR+Zqw2SPXoRFEpuEX2DgJSQHxccBhsq9sFevUn00MPTPBaQnRPn1P2z8FUPsFa+Eihkf6POlLAcEahtw8KzzyykbnYI45a+qV7A12cBwO4RLVKM661XyeRo+n2PW7kpDi1nt8Q=,iv:lgrfuCQyamPONQuXY1/qsW9QsEcUU0zATMWHmVM4guo=,tag:P7LNTyB2P7zdwkh9Kljzgw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
