---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  namespace: mediabox
  labels:
    app: "jellyfin"
    app.kubernetes.io/instance: "jellyfin"
    app.kubernetes.io/name: "jellyfin"
    release: "jellyfin"
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 64Gi
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: mediabox
  labels:
    app: "jellyfin"
    app.kubernetes.io/instance: "jellyfin"
    app.kubernetes.io/name: "jellyfin"
    release: "jellyfin"
    service.name: "main"
spec:
  type: ClusterIP
  publishNotReadyAddresses: false
  ports:
    - name: main
      port: 8096
      protocol: TCP
      targetPort: 8096
  selector:
    pod.name: main
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/instance: jellyfin
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin-autodiscovery
  namespace: mediabox
  labels:
    app: "jellyfin"
    app.kubernetes.io/instance: "jellyfin"
    app.kubernetes.io/name: "jellyfin"
    release: "jellyfin"
    service.name: "autodiscovery"
spec:
  type: ClusterIP
  publishNotReadyAddresses: false
  ports:
    - name: autodiscovery
      port: 7359
      protocol: UDP
      targetPort: 7359
  selector:
    pod.name: main
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/instance: jellyfin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: mediabox
  labels:
    app: "jellyfin"
    app.kubernetes.io/instance: "jellyfin"
    app.kubernetes.io/name: "jellyfin"
    release: "jellyfin"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      pod.name: main
      app.kubernetes.io/name: jellyfin
      app.kubernetes.io/instance: jellyfin
  template:
    metadata:
      labels:
        app: "jellyfin"
        app.kubernetes.io/instance: "jellyfin"
        app.kubernetes.io/name: "jellyfin"
        pod.lifecycle: "permanent"
        pod.name: "main"
        release: "jellyfin"
      annotations:
        checksum/cnpg: "12c2f2443588dc1ade2410eac85c5b0b1751a3c6abef1e92e3aebf8896f77509"
        checksum/configmaps: "44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a"
        checksum/mariadb: "09c85576cb45b1eecd1467732b11ea8fa3363b0105c465f02a6ad64991521d52"
        checksum/mongodb: "09c85576cb45b1eecd1467732b11ea8fa3363b0105c465f02a6ad64991521d52"
        checksum/persistence: "3b59f2976681401889147a54db8b823729b6154ac8475535f06e2346180158fc"
        checksum/redis: "013343a028cbb3f7e08f4ba7522702dd98e52632c688641074b0b1db3df29894"
        checksum/secrets: "44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a"
        checksum/services: "8bc7cf1c7b30a068a71f13f174f3d9754e6232bfa6096a5a6be4003b7ab81423"
        checksum/solr: "29c14feeaddbf7762052db593898d274941f539cee681ddc613957587686f347"
    spec:
      serviceAccountName: default
      automountServiceAccountToken: false
      runtimeClassName:
      hostNetwork: false
      hostPID: false
      hostIPC: false
      shareProcessNamespace: false
      enableServiceLinks: false
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/arch: amd64
      topologySpreadConstraints:
        - maxSkew: 1
          whenUnsatisfiable: ScheduleAnyway
          topologyKey: "kubernetes.io/hostname"
          labelSelector:
            matchLabels:
              pod.name: main
              app.kubernetes.io/name: jellyfin
              app.kubernetes.io/instance: jellyfin
          nodeAffinityPolicy: Honor
          nodeTaintsPolicy: Honor
      dnsPolicy: ClusterFirst
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      terminationGracePeriodSeconds: 60
      securityContext:
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups:
          - 109
        sysctls: []
      hostUsers: true
      containers:
        - name: jellyfin
          image: docker.io/jellyfin/jellyfin:10.8.13@sha256:05a9734d7e83086b957c5b7a16cbb5a60b5bb8d113ffb953e57547359dd05140
          imagePullPolicy: IfNotPresent
          tty: false
          stdin: false
          ports:
            - name: autodiscovery
              containerPort: 7359
              protocol: UDP
              hostPort: null
            - name: main
              containerPort: 8096
              protocol: TCP
              hostPort: null
          volumeMounts:
            - name: cache
              mountPath: /cache
              readOnly: false
            - name: config
              mountPath: /config
              readOnly: false
            - name: devshm
              mountPath: /dev/shm
              readOnly: false
            - name: shared
              mountPath: /shared
              readOnly: false
            - name: tmp
              mountPath: /tmp
              readOnly: false
            - name: transcode
              mountPath: /config/transcodes
              readOnly: false
            - name: varlogs
              mountPath: /var/logs
              readOnly: false
            - name: varrun
              mountPath: /var/run
              readOnly: false
          livenessProbe:
            httpGet:
              port: 8096
              path: /
              scheme: HTTP
            initialDelaySeconds: 12
            failureThreshold: 5
            successThreshold: 1
            timeoutSeconds: 5
            periodSeconds: 15
          readinessProbe:
            httpGet:
              port: 8096
              path: /
              scheme: HTTP
            initialDelaySeconds: 10
            failureThreshold: 4
            successThreshold: 2
            timeoutSeconds: 5
            periodSeconds: 12
          startupProbe:
            httpGet:
              port: 8096
              path: /
              scheme: HTTP
            initialDelaySeconds: 10
            failureThreshold: 60
            successThreshold: 1
            timeoutSeconds: 3
            periodSeconds: 5
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
            limits:
              cpu: 4000m
              memory: 8Gi
          securityContext:
            runAsNonRoot: true
            runAsUser: 568
            runAsGroup: 568
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: true
            privileged: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              add: []
              drop:
                - ALL
          env:
            - name: "TZ"
              value: "UTC"
            - name: "UMASK"
              value: "0022"
            - name: "UMASK_SET"
              value: "0022"
            - name: "NVIDIA_VISIBLE_DEVICES"
              value: "void"
            - name: "S6_READ_ONLY_ROOT"
              value: "1"
            - name: "JELLYFIN_PublishedServerUrl"
              value: "http://127.0.0.1:8096"
      volumes:
        - name: cache
          emptyDir: {}
        - name: config
          persistentVolumeClaim:
            claimName: jellyfin-config
        - name: devshm
          emptyDir:
            medium: Memory
            sizeLimit: 8Gi
        - name: shared
          emptyDir: {}
        - name: tmp
          emptyDir:
            medium: Memory
            sizeLimit: 8Gi
        - name: transcode
          emptyDir: {}
        - name: varlogs
          emptyDir:
            medium: Memory
            sizeLimit: 8Gi
        - name: varrun
          emptyDir:
            medium: Memory
            sizeLimit: 8Gi
