---
apiVersion: v1
kind: Service
metadata:
  name: mediabox-lb
  namespace: mediabox
  labels:
    app.kubernetes.io/instance: "mediabox"
    app.kubernetes.io/name: "mediabox"
    app: "mediabox"
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8096
    - name: radarr
      port: 7878
      protocol: TCP
      targetPort: 7878
    - name: sonarr
      port: 8989
      protocol: TCP
      targetPort: 8989
  selector:
    app: "mediabox"
