---
apiVersion: v1
kind: Namespace
metadata:
  name: cattle-system
  labels:
    name: cattle-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: rancher
  namespace: flux-system
spec:
  interval: 60m
  url: https://releases.rancher.com/server-charts/stable
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  chart:
    spec:
      chart: rancher
      sourceRef:
        kind: HelmRepository
        name: rancher
        namespace: flux-system
  interval: 60m
  values:
    hostname: rancher.layertwo.dev
    noProxy: 127.0.0.0/8,10.0.0.0/8,cattle-system.svc,172.16.0.0/12,192.168.0.0/16,.svc,.cluster.local
    ingress:
      tls:
        source: secret
        secretName: tls-rancher-ingress
      extraAnnotations:
        cert-manager.io/issuer-kind: ClusterIssuer
        cert-manager.io/issuer-name: letsencrypt-prod-dns
      ingressClassName: traefik-internal
    privateCA: false
