---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-radarr-config
  namespace: mediabox
spec:
  storageClassName: sunbeam-nfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 16Gi
