name: Docker Image CI

on:
  push:
    branches: [ "mainline" ]
    paths:
      - containers/bird/**
  pull_request:
    branches: [ "mainline" ]
    paths:
      - containers/bird/**

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      working-directory: containers/bird
      run: docker build . --file Dockerfile --tag bird:latest
